
# This is the main configuration file for Supabase CLI.
project_id = "fzcyzjruixuriqzryppz"

[api]
# Port for the API gateway
port = 54321
# Default API schemas
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
# to use webhooks in local development, set the api.webhooks.config under localhost.
max_rows = 1000

[db]
# Port for the SQL editor
port = 54322
# Port for the DB connection
major_version = 15

[studio]
# Port for Supabase Studio
port = 54324

[functions]
# Port for the Functions service
port = 54342

# Configure individual functions
[functions.create-payment-intent]
verify_jwt = true

[functions.retrieve-payment-intent]
verify_jwt = true

[functions.check-connect-account]
verify_jwt = true

[functions.create-connect-account]
verify_jwt = true

[functions.confirm-session-complete]
verify_jwt = true

[functions.fetch-usc-courses]
verify_jwt = false

[functions.query_term_courses]
verify_jwt = true

[functions.query_terms]
verify_jwt = true

[functions.send-session-emails]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.get-stripe-config]
verify_jwt = false
